steps:

- name: 'docker/compose:1.26.2'
  args: ['up', '-d', '--build']

- name: 'docker'
  args: ['exec', 'app', 'bash','composer','install']

- name: 'docker'
  args: ['exec', 'app', 'bash','cp','/var/www/.env.example','/var/www/.env']

- name: 'docker'
  args: ['exec', 'app', 'bash','php','artisan','key:generate']

- name: 'docker'
  args: ['exec', 'app', 'bash','php','artisan','migrate']

- name: 'docker'
  args: ['exec', 'app', 'bash','php','artisan','test','--group=feature','--stop-on-failure']

# Push the new image to the registry.
images: ['gcr.io/fast-art-289820/workspace_app:latest']