steps:

- name: 'docker/compose:1.26.2'
  args: ['up', '-d', '--build']

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_app:latest', 'gcr.io/fast-art-289820/workspace_app:$SHORT_SHA']

- name: 'docker'
  args: ['exec', 'app', 'composer','install']

- name: 'docker'
  args: ['exec', 'app', 'cp','/var/www/.env.example','/var/www/.env']

- name: 'docker'
  args: ['exec', 'app', 'php','artisan','key:generate']

- name: 'docker'
  args: ['exec', 'app', 'php','artisan','migrate']

- name: 'docker'
  args: ['exec', 'app', 'php','artisan','test','--group=feature','--stop-on-failure']

# Push the new image to the registry.
images: ['gcr.io/fast-art-289820/workspace_app:$SHORT_SHA']