steps:

- name: 'docker/compose:1.26.2'
  args: ['up', '-d', '--build']

- name: 'docker'
  args: ['push', 'workspace_app:latest']

- name: 'docker'
  args: ['exec', 'workspace_app', 'bash','composer','install']

- name: 'docker'
  args: ['exec', 'workspace_app', 'bash','cp','/var/www/.env.example','/var/www/.env']

- name: 'docker'
  args: ['exec', 'workspace_app', 'bash','php','artisan','key:generate']

- name: 'docker'
  args: ['exec', 'workspace_app', 'bash','php','artisan','migrate']

- name: 'docker'
  args: ['exec', 'workspace_app', 'bash','php','artisan','test','--group=feature','--stop-on-failure']