steps:

#Step 0
- name: 'docker/compose:1.19.0'
  args: ['up', '-d', '--build']

#Step 1
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_app:latest', 'gcr.io/fast-art-289820/app:$SHORT_SHA']

# Push the new image to the registry.
  images: ['gcr.io/fast-art-289820/app:$SHORT_SHA']

#Step 2
- name: 'docker/compose:1.19.0'
  args: ['exec', 'app', 'bash','composer','install']

#Step 3
- name: 'docker/compose:1.19.0'
  args: ['exec', 'app', 'bash','cp','/var/www/.env.example','/var/www/.env']

#Step 4
- name: 'docker/compose:1.19.0'
  args: ['exec', 'app', 'bash','php','artisan','key:generate']

#Step 5
- name: 'docker/compose:1.19.0'
  args: ['exec', 'app', 'bash','php','artisan','migrate']

#Step 6
- name: 'docker/compose:1.19.0'
  args: ['exec', 'app', 'bash','php','artisan','test','--group=feature','--stop-on-failure']