version: '3'
services:
  app:
    build: .
    container_name: app
    volumes:
      - ./:/var/www
    networks:
      - app-network      

  nginx:
    build: ./.docker/nginx
    restart: always
    container_name: nginx
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network    

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379
    networks:
      - app-network

  db:
    build: ./.docker/mysql
    command: --innodb-use-native-aio=0
    restart: always
    container_name: db
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment: 
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network            

networks:
  app-network: 
    driver: bridge

  
