apiVersion: apps/v1
kind: Deployment
metadata:
  name: app

spec:
  selector:
    matchLabels:
      app: app

  template:
    metadata:
      labels:
        app: app

    spec:
      containers:
      - name: app
        image: img-app-deployment #9324015768815731/fabricio-laravel:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 80

        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: ROOT_PASSWORD

        envFrom:
        - configMapRef:
            name: app-conf

        volumeMounts:
        - name: app-conf
          mountPath: /var/www/.env
          subPath: .env #cria o arquivo mesmo se ele já existir

      volumes:
      - name: app-conf
        configMap:
          name: app-conf
          items:
            - key: env
              path: .env